In [2]:
import cv2
import numpy as np
import random
import matplotlib.pyplot as plot

In [6]:
print(random.randint(0,9))

1


In [7]:
rw, cl = input("Enter the size of the image: ").split()
rw = int(rw)
cl = int(cl)
print(rw)
print(cl)

Enter the size of the image: 1000 500
1000
500


In [8]:
custom_image = np.random.randint(0, 255, (cl, rw, 3))
custom_image = custom_image.astype(float)
print(custom_image)
print(type(custom_image))

[[[248.  57.  43.]
  [ 33.  43.  76.]
  [136. 132.  26.]
  ...
  [226. 169. 187.]
  [157. 216. 189.]
  [106. 143. 111.]]

 [[240. 140.  65.]
  [207. 214. 155.]
  [ 57.  77.   5.]
  ...
  [ 47.  33.  96.]
  [214. 223. 174.]
  [181. 157.   0.]]

 [[  5.   9.   5.]
  [188. 246. 218.]
  [ 93. 205.  36.]
  ...
  [199.  82.  75.]
  [ 38. 197.  18.]
  [121.  43. 230.]]

 ...

 [[245.  81. 200.]
  [187. 231. 233.]
  [ 38.  96. 144.]
  ...
  [ 90. 135. 167.]
  [213. 145.  33.]
  [130. 114.  97.]]

 [[127. 250.  63.]
  [207. 153.  13.]
  [  3.   1.  56.]
  ...
  [252. 212.  34.]
  [231. 158. 194.]
  [ 38. 243. 197.]]

 [[185. 194. 101.]
  [ 57. 188. 162.]
  [146. 228.  84.]
  ...
  [ 69.  72. 105.]
  [184. 155. 230.]
  [138. 226. 161.]]]
<class 'numpy.ndarray'>


In [9]:
custom_image.shape

(500, 1000, 3)

In [10]:
cv2.imshow("Custom Created Image", custom_image)
cv2.waitKey(0) == 13
cv2.destroyAllWindows()

In [11]:
cv2.imwrite("CustomImage.jpg",custom_image)

True